spring:
  redis:
    host: 127.0.0.1
    port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/jpa?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    password: 123456

  jpa:
    show-sql: true  #打印输出sql执行信息
    hibernate:
      ddl-auto: update